name: Entheo Music
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60999
title: ENTHEO MUSIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#625142'
    - '#120a07'
    - '#cebc91'
    - '#a97746'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
