name: Entheo Music
favicon: null
layout_spectrum: 0.396991633111611
typography_spectrum: 0.3824047257658094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#625142'
    - '#120a07'
    - '#cebc91'
    - '#a97746'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9094711327925324
  rhythmicContrast: 0
purpose: []
