name: Entheo Music
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: ENTHEO MUSIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#625142'
    - '#120a07'
    - '#cebc91'
    - '#a97746'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.9094711327925324
  rhythmicContrast: 0
purpose: []
